# Generated by Django 3.0.2 on 2021-03-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20210311_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='author',
        ),
    ]
