# Generated by Django 3.0.2 on 2021-03-11 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0008_status_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='reaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frommaterial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='author',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, related_name='tomaterial', to=settings.AUTH_USER_MODEL),
        ),
    ]
