# Generated by Django 3.0.2 on 2021-03-11 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0010_auto_20210311_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='reaction',
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frommaterial', to=settings.AUTH_USER_MODEL),
        ),
    ]
