# Generated by Django 3.0.2 on 2021-03-22 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0013_auto_20210322_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frommaterial', to=settings.AUTH_USER_MODEL),
        ),
    ]
