# Generated by Django 3.0.2 on 2021-03-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0015_auto_20210323_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='Like',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Like', to='status.Status'),
        ),
    ]
