# Generated by Django 3.0.2 on 2021-03-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0019_status_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='DisLike',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='reaction',
            name='Status_Post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Like', to='status.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='Like',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
